In [29]:
# math library - 교재 400~

In [2]:
import math

In [4]:
math.pi

3.141592653589793

In [7]:
math.pow(2, 10)

1024.0

In [8]:
math.ceil(2.345)

3

In [9]:
math.floor(2.345)

2

In [11]:
math.sin(0)

0.0

In [12]:
math.sin(math.pi)

1.2246467991473532e-16

In [13]:
math.sin(math.pi/2)

1.0

In [69]:
# numpy

import numpy as np

In [15]:
np.pi

3.141592653589793

In [17]:
np.power(2, 10)

np.int64(1024)

In [26]:
np.round(2.345, 2)

np.float64(2.35)

In [18]:
np.ceil(2.345)

np.float64(3.0)

In [19]:
np.floor(2.345)

np.float64(2.0)

In [20]:
np.sin(0)

np.float64(0.0)

In [21]:
np.sin(math.pi)

np.float64(1.2246467991473532e-16)

In [22]:
np.sin(math.pi/2)

np.float64(1.0)

In [23]:
np.cos(0)

np.float64(1.0)

In [24]:
np.cos(math.pi)

np.float64(-1.0)

In [25]:
np.cos(math.pi/2)

np.float64(6.123233995736766e-17)

In [27]:
round(2.345)

2

In [28]:
round(2.345, 2)

2.35

In [73]:
np.random.randint(1, 10, 3)

# low, high, size

array([3, 1, 2], dtype=int32)

In [76]:
np.random.choice([1,2,3,4,5], 3)

# a(리스트), size, 

array([2, 5, 2])

In [78]:
np.random.choice([1,2,3,4,5], 3, replace=False)

# a(리스트), size, 
# replace=False 를 써주면 중복된 숫자는 나오지 않는다.

array([1, 2, 5])

In [108]:
# random 라이브러리

import random

In [32]:
random.random()

# 0-1 까지 랜덤으로 매번 다른 숫자 표기.

0.5206477737831167

In [33]:
random.random()*10

5.186488729813744

In [34]:
random.random()*100

15.120833411489665

In [39]:
random.random()*2 + 1

# (b-a) 를 곱하고 시작하는 수만큼 더해준다.

2.7618751783870406

In [38]:
random.uniform(1, 3)

# 1 과 3 사이의 숫자를 랜덤으로
# random.random()*2 + 1 과 같은 함수

2.1317814184103874

In [40]:
random.randint(1, 3)

# out put 을 int 정수로 뽑고 싶을 때 

3

In [64]:
random.randint(1, 10)
li = []
for i in range(5):
    li.append(random.randint(1, 10))

li

# 1- 10까지 출력, 중복 허용

[8, 5, 2, 9, 5]

In [65]:
random.randrange(1, 3)

# 1 ~ 9까지 출력

1

In [67]:
random.randrange(1, 10, 2)

# 1 ~ 9까지 중 홀수 출력

9

In [41]:
li = [1, 2, 3]

random.shuffle(li)
li

[1, 3, 2]

In [43]:
li = list(range(10))

random.shuffle(li)
li

# 셔플은 따로 저장하지 않는다. 

[4, 9, 3, 8, 0, 1, 7, 5, 6, 2]

In [53]:
random.seed(4) # 시드, 씨앗, 시드머니, 마중물 (물 끌어올리는 펌프)

In [54]:
random.random()

# 시드 값 주면 같은 값 나옴.

0.23604808973743452

In [56]:
random.sample([1, 2, 3], k=2)

# 리스트안에 숫자중 아무거나 2개 출력

[2, 1]

In [114]:
random.sample(range(10), k=5)

[8, 9, 7, 5, 2]

In [110]:
random.choice([1,2,3,4,5])

5

In [111]:
random.choices([1,2,3,4,5], k=2)

[1, 3]

In [113]:
random.choices([1,2,3,4,5], k=4)

[4, 1, 3, 5]

In [68]:
random.normalvariate(5, 2)

# (mu = 평균, sigma = 표준편차)
# 표준편차가 높을(클) 수록 곡선이 완만해진다.

6.021517679241907

### os 모듈

- 현재 위치
- 디렉토리 이동
- 디렉토리 안에 파일 목록 보기
- 파일 이름 바꾸기, 삭제하기

In [79]:
import os

In [82]:
os.getcwd()

# 현재 작업하는 주소 current working directory

'C:\\Users\\User\\Desktop\\0323'

In [86]:
os.chdir('C:/Users/User/Desktop')

# 주소 옮기기

In [85]:
os.getcwd()

'C:\\Users\\User\\Desktop'

In [87]:
os.listdir()

['.ipynb_checkpoints',
 '0312_변수내용.ipynb',
 '0323',
 'basic.txt',
 'desktop.ini',
 'Firefox.exe',
 'Microsoft Edge.lnk',
 'test.txt',
 'today.txt',
 '★ 파이썬 총 정리.ipynb',
 '★ 파이썬_교수님0311.ipynb',
 '사전수업',
 '정규수업',
 '정리 진도.txt']

In [95]:
os.mkdir("test001")

# 만들기

In [96]:
os.rmdir("test001")

# 삭제

In [89]:
os.listdir()

['.ipynb_checkpoints',
 '0312_변수내용.ipynb',
 '0323',
 'basic.txt',
 'desktop.ini',
 'Firefox.exe',
 'Microsoft Edge.lnk',
 'test.txt',
 'test001',
 'today.txt',
 '★ 파이썬 총 정리.ipynb',
 '★ 파이썬_교수님0311.ipynb',
 '사전수업',
 '정규수업',
 '정리 진도.txt']

In [90]:
os.rename()

TypeError: rename() missing required argument 'src' (pos 1)

In [91]:
os.remove()

TypeError: remove() missing required argument 'path' (pos 1)

In [8]:
import urllib

In [101]:
html = urllib.request.urlopen("http://www.naver.com")

In [102]:
type(html)

http.client.HTTPResponse

In [103]:
html.read()

b'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta property="og:title" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="\xeb\x84\xa4\xec\x9d

In [105]:
html = urllib.request.urlopen("http://www.naver.com").read()
html

b'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta property="og:title" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="\xeb\x84\xa4\xec\x9d

In [3]:
# requests 라는 외장 라이브러리도 있다.
# install 완료.

In [4]:
html = requests.get("http://www.naver.com").text

In [5]:
pip install beautifulsoup4

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [7]:
from bs4 import BeautifulSoup

# 함수가 아니라 클래스임

In [11]:
# 'html.parser' 해석기

soup = BeautifulSoup(html, 'html.parser')
soup

# 위에 html을 잘 정리해서 보기

 <!DOCTYPE html>
 <html class="fzoom" lang="ko"> <head> <meta charset="utf-8"/> <meta content="origin" name="Referrer"/> <meta content="IE=edge" http-equiv="X-UA-Compatible"/> <meta content="width=1190" name="viewport"/> <title>NAVER</title> <meta content="NAVER" name="apple-mobile-web-app-title"> <meta content="index,nofollow" name="robots"> <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description"> <meta content="네이버" property="og:title"/> <meta content="https://www.naver.com/" property="og:url"/> <meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/> <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description"> <meta content="summary" name="twitter:card"/> <meta content="" name="twitter:title"/> <meta content="https://www.naver.com/" name="twitter:url"/> <meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" name="twitter:image"/> <meta content="네이버 메인에서 다양한 

In [12]:
url = "https://www.naver.com"
url = http://www.kma.go.kr/weathe/forecast/mid-term-rss3.jsp?stnId=108.com
html = requests.get(url).text

SyntaxError: invalid decimal literal (1131720358.py, line 2)

In [13]:
!pip install Faker

   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 29.9 MB/s  0:00:00



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [13]:
## faker 

from faker import Faker

In [14]:
fake = Faker()

In [18]:
fake.name()

'Michael Murray'

In [19]:
for i in range(5):
    print(fake.name())

Megan Anderson
Kimberly Henry
Kevin Mckay
Edward Owens
April Johnson


In [20]:
fake.address()

'4933 Lucas Lane Suite 779\nBradland, AK 98295'

In [21]:
fake.phone_number()

'289.424.1727x15964'

In [15]:
fake = Faker('ko-kr')

In [23]:
fake.name()

'이우진'

In [24]:
for i in range(5):
    print(fake.name())

김중수
이주원
남재호
김지훈
박보람


In [25]:
fake.address()

'강원도 광주시 석촌호수6거리 지하669'

In [26]:
fake.phone_number()

'062-722-4535'

In [27]:
for i in range(5):
    print(fake.name())
    print(fake.address())
    print(fake.phone_number())

박옥순
세종특별자치시 서구 서초대로 466
052-347-4270
김예준
대구광역시 마포구 서초중앙거리 823-33
063-019-4647
황수민
인천광역시 도봉구 백제고분0가 지하90
064-769-2815
이은지
충청남도 청주시 흥덕구 학동길 914 (순자강윤읍)
033-726-4409
김현지
경기도 안양시 만안구 도산대로 지하703
011-532-1028


In [16]:
li = []

for i in range(5):
    li.append((fake.name(), fake.address(), fake.phone_number()))

li

[('홍영환', '광주광역시 강서구 양재천181거리 지하439 (정자양허동)', '041-936-3747'),
 ('권성호', '경상남도 시흥시 석촌호수거리 524 (지아안면)', '061-923-5898'),
 ('이준호', '전라북도 수원시 팔달구 가락길 798-90 (은서김홍리)', '010-8759-6440'),
 ('김정웅', '전라남도 부천시 원미구 오금576길 362-20 (건우박이면)', '016-899-2988'),
 ('박영철', '제주특별자치도 의왕시 역삼60로 805-77', '031-385-7861')]

In [18]:
with open("test1.txt", 'w') as f:
    for i in range(5):
        f.write( fake.name())
        f.write( fake.phone_number())
        f.write("\n")

In [33]:
li = [ ((fake.name(), fake.address()) for i in range(5) )]
li

[<generator object <genexpr> at 0x00000224146D8820>]

In [34]:
!pip install sympy

   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ---------------------------------------  6.3/6.3 MB 54.4 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 41.3 MB/s  0:00:00
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 13.2 MB/s  0:00:00

   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   ------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [35]:
# sympy_test.py

from fractions import Fraction
import sympy

# 가지고 있던 돈을 x라고 하자.
x = sympy.symbols("x")

# 가지고 있던 돈의 2/5가 1760원이므로 방정식은 x * (2/5) = 1760 이다.
f = sympy.Eq(x*Fraction('2/5'), 1760)

# 방정식을 만족하는 값(result)을 구한다.
result = sympy.solve(f)  # 결괏값은 리스트

# 남은 돈은 다음과 같이 가지고 있던 돈에서 1760원을 빼면 된다.
remains = result[0] - 1760

print('남은 돈은 {}원 입니다.'.format(remains))

남은 돈은 2640원 입니다.


In [38]:
import sympy
x = sympy.symbols("x")
f = sympy.Eq(x**2, 1)
sympy.solve(f)

[-1, 1]

In [40]:
import sympy
x, y = sympy.symbols('x y')
f1 = sympy.Eq(x+y, 10)
f2 = sympy.Eq(x-y, 4)
sympy.solve([f1, f2])

{x: 7, y: 3}

In [5]:
PI = 3.1415926

print("Hello")

def circum(r):
    return 2*PI*r
    
print(circum(10))

Hello
62.831852


In [6]:
def add(a, b):
    return a + b

print(add(10, 20))

30


In [7]:
if __name__ == "__main__":
    print(circum(10))
    print(add(10, 20))

62.831852
30


In [2]:
__a__ = "Hello"
print(__a__)

Hello


In [8]:
# module.py 안에 있는 모든 코드가 실행된다.
# 단, if __name__ == "__main__": 이하 부분은 실행되지 않는다.